name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build the Electron app
        run: npm run build  # Assuming "build" is the script in package.json for building your app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Package app for Windows
        run: npx electron-builder --win nsis -c.extraMetadata.version=${{ github.event.release.tag_name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/*.exe'  # Path to your built .exe file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
